### ISSUE TITLE
Add arbGeomParams to newly created object

### ISSUE THREAD

**Issue by alex-v-dev** [alembic/cask#8]
Hi,

I'm trying to add properties under .geom/.arbGeomParams on an Archive i create from scratch, but it seems that my properties do not get saved. Also, if i query the properties of my object I get an empty list.

Is this supported at all ?

Thanks !

**Comment by rsgalloway** [comment]
Hi, thanks for the question. Looks like currently it's not working for geom objects, but wouldn't be hard to support. Here's a quick test I did, is this what you mean?

```
>>> a = cask.Archive()
>>> a.top.children["meshy"] = cask.PolyMesh()
>>> a.top.children["meshy"].properties[".geom/.arbGeomParams/test"] = cask.Property()
>>> a.top.children["meshy"].properties[".geom/.arbGeomParams/test"].set_value("somevalue")
>>> a.write_to_file("test.abc")
```

$ abcls test.abc/meshy/.geom/.arbGeomParams/test/1
somevalue

**Comment by alex-v-dev** [comment]
Hi, what a quick response time ! :D

Yes, this is exactly what i'm trying to do ! It doesn't error out, but the property is not there when i look at the ABC in abcecho.

**Comment by rsgalloway** [comment]
That's because when writing geom objects, the ".geom/.arbGeomParams" property was being overwritten by alembic. I have a proposed patch here, which you can try:

http://github.com/rsgalloway/cask

Will post for code review shortly to get this fix into the official version.

**Comment by alex-v-dev** [comment]
AMAZING !

Thanks you so much !
It seems to work with ints and strings, but I'm unsure on how to set an array of V3f for example, i get this message : 
`Error setting value on rotation: <imath.V3fArray object at 0x00000214B5807048> <class 'alembic.Abc.OArrayProperty'>
No registered converter was able to produce a C++ rvalue of type class Alembic::Abc::v7::TypedArraySample<struct Alembic::Abc::v7::Float32TPTraits> from this Python object of type V3fArray`

I'm very likely doing it wrong though.
BTW, big fan of pyseq here :)

**Comment by rsgalloway** [comment]
No, that looks like another bug. Will look into it further and post an update soon if I can.

**Comment by rsgalloway** [comment]
OK, pushed another update to my dev branch. Pull that, and let me know that fixes this for you.

**Comment by alex-v-dev** [comment]
It works ! Perfect, thanks a thousand times !

I'm curious how you'd set Geometry Scope and ArrayExtend kind of stuff properly (so that Houdini can read the attributes for example). Right now it works by hacking the metadata dict but that seems weird :)

**Comment by rsgalloway** [comment]
No, setting keys in the metadata is pretty much the way to do it, at least for now. There's some logic for specific properties like .selfBnds and .childBnds to set the interpretation automatically, and it also tries to be smart about array extent, for example.

**Comment by alex-v-dev** [comment]
Cool, it works just fine anyways.

Another question if you don't mind, I'm setting a bunch of samples, and then setting the properties, but it looks like they have a different TimeSampling in the end, as when I playback in Houdini the positions are fine, but the properties are moving super slow. Is this normal ?

**Comment by rsgalloway** [comment]
Are you creating and adding a new TimeSampling object on the archive, and then setting the id on the properties?

`>>> p = cask.Property(..., time_sampling_id=1)`

**Comment by alex-v-dev** [comment]
Niice it works by defining the time_sampling_id ! Actually I don't get how to create a TimeSampling object for the Archive, there's very few info on that on the original API
